services:
  zipkin:
    image: openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    ports:
      - "9411:9411"
  postgres:
    container_name: postgres
    image: postgres:14.9
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Amir123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge


volumes:
  postgres: